apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../stable
images:
- name: registry.k8s.io/sig-storage/csi-node-driver-registrar
  newName: gcr.io/gke-release/csi-node-driver-registrar
  newTag: v1.2.0-gke.0
- name: registry.k8s.io/sig-storage/csi-provisioner
  newName: gcr.io/gke-release/csi-provisioner
  newTag: v1.6.0-gke.0
- name: registry.k8s.io/sig-storage/csi-resizer
  newName: gcr.io/gke-release/csi-resizer
  newTag: v0.5.0-gke.0
